openapi: 3.0.3
info:
  title: Joy Calendar API
  description: API for content calendar operations
  version: 2.0.0

servers:
  - url: /api
    description: API base path

security:
  - bearerAuth: []
  - magicLinkAuth: []

paths:
  /calendar/month:
    get:
      summary: Get content items for a specific month
      operationId: getCalendarMonth
      tags:
        - Calendar
      parameters:
        - name: client_id
          in: query
          required: false
          schema:
            type: integer
          description: Client ID (required for admin/agency users)
        - name: year
          in: query
          required: true
          schema:
            type: integer
            minimum: 2020
            maximum: 2100
        - name: month
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        '200':
          description: Calendar month data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarMonthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /calendar/range:
    get:
      summary: Get content items for a date range
      operationId: getCalendarRange
      tags:
        - Calendar
      parameters:
        - name: client_id
          in: query
          required: false
          schema:
            type: integer
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Calendar range data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarRangeResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'

  /calendar/stats:
    get:
      summary: Get calendar statistics
      operationId: getCalendarStats
      tags:
        - Calendar
      parameters:
        - name: client_id
          in: query
          required: false
          schema:
            type: integer
        - name: year
          in: query
          required: true
          schema:
            type: integer
        - name: month
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        '200':
          description: Calendar statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarStatistics'

components:
  schemas:
    CalendarMonthResponse:
      type: object
      required:
        - month
        - content_items
        - grouped_by_date
      properties:
        month:
          type: string
          format: date
          example: "2025-10"
        content_items:
          type: array
          items:
            $ref: '#/components/schemas/ContentItem'
        grouped_by_date:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/ContentItem'
        statistics:
          $ref: '#/components/schemas/CalendarStatistics'

    CalendarRangeResponse:
      type: object
      required:
        - start_date
        - end_date
        - content_items
      properties:
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        content_items:
          type: array
          items:
            $ref: '#/components/schemas/ContentItem'

    CalendarStatistics:
      type: object
      properties:
        completion_rate:
          type: number
          format: float
          minimum: 0
          maximum: 100
          example: 75.5
        busiest_day:
          type: string
          format: date
          example: "2025-10-15"
        platform_distribution:
          type: object
          additionalProperties:
            type: integer
          example:
            facebook: 10
            instagram: 8
            linkedin: 5
        status_breakdown:
          type: object
          properties:
            draft:
              type: integer
            pending_review:
              type: integer
            approved:
              type: integer
            published:
              type: integer

    ContentItem:
      type: object
      required:
        - id
        - title
        - scheduled_date
        - status
        - platform
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: "Fall Product Launch Post"
        description:
          type: string
          nullable: true
        scheduled_date:
          type: string
          format: date-time
        status:
          type: string
          enum: [draft, pending_review, approved, published, rejected]
        platform:
          type: string
          enum: [facebook, instagram, linkedin, blog]
        image_url:
          type: string
          format: uri
          nullable: true
        comments_count:
          type: integer
          example: 3
        created_at:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Unauthorized"

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Forbidden"

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Validation failed"
            errors:
              start_date: ["The start date field is required."]

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    magicLinkAuth:
      type: apiKey
      in: query
      name: token
